paginatePath: pullRequests.edges.node

name-template: 'ğŸ”– MockUp Moonlighter v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'âœ¨ ì¶”ê°€ëœ ê¸°ëŠ¥'
    labels:
      - 'enhancement'
  - title: 'ğŸ› ë²„ê·¸ í”½ìŠ¤'
    labels:
      - 'bug'
      - 'fix'
  - title: 'ğŸ”§ ì½”ë“œ ê°œì„ '
    label:
      - 'chore'
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## No Lable Changes

  $CHANGES